blank_issues_enabled: false
contact_links:
  - name: MyDivinations Team Discussion
    url: https://github.com/Digidinc/Mydiv/discussions
    about: For general questions and discussions not related to bugs or feature requests
