name: Astrology Engine CI

on:
  push:
    branches: [ main ]
    paths:
      - 'services/astrology-engine/**'
      - '.github/workflows/astrology-engine-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/astrology-engine/**'
      - '.github/workflows/astrology-engine-ci.yml'

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./services/astrology-engine
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt
    
    - name: Run flake8
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting with black
      run: |
        black --check src
    
    - name: Check imports with isort
      run: |
        isort --check-only --profile black src
  
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./services/astrology-engine
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov hypothesis
    
    - name: Run tests with pytest
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./services/astrology-engine/coverage.xml
        flags: astrology-engine
        name: codecov-astrology-engine
        fail_ci_if_error: false

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./services/astrology-engine
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./services/astrology-engine
        push: false
        load: true
        tags: mydiv/astrology-engine:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Test Docker image
      run: |
        docker image inspect mydiv/astrology-engine:test
