name: Sync Labels

on:
  push:
    paths:
      - '.github/labels.json'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.json
          token: ${{ secrets.GITHUB_TOKEN }}
          prune: false
